baseURL = "http://localhost:1313/"
title = "hanlove"
languageCode = "zh-cn"

# 采用免环境、绝对不会塌陷的 1:1 Blowfish 纯白精美排版
[params]
  colorScheme = "blowfish"
  layoutLoop = "card"

[menu]
  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "关于"
    url = "#"
    weight = 2
  [[menu.main]]
    name = "归档"
    url = "#"
    weight = 3
